version: '3.7'
services:
  nginx:
    build:
      context: nginx
      target: developer
    ports:
      - 8080:80
    depends_on:
      - app
  app:
    build:
      context: app
      target: developer
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
